[package]
name = "gapper"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
rstest = "0.24.0"
rstest_reuse = "0.7.0"
rand = "0.9.0"

[dependencies]
bytemuck = { version = "1.21.0", features = ["zeroable_maybe_uninit", "must_cast", "min_const_generics"] }
