name: Run tests
run-name: ${{ github.ref }} 
on: 
  pull_request:
    types: [opened, edited]
    paths:
      - '**.rs'
      - '**.toml'
  push:
    types: []
    paths:
      - '**.rs'
      - '**.toml'

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cache
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Quick Lint
        run: cargo check --all-features
      - name: Lint
        run: cargo clippy --all-features
      - name: Tests
        run: cargo test --all-features
      - name: Machete
        uses: bnjbvr/cargo-machete@main
      - run: rustup component add miri
      - name: Miri Tests
        run: cargo +nightly miri test 
        
