name: Run tests
run-name: ${{ github.ref }} 
on: 
  pull_request:
    types: [opened, edited]
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'
  push:
    types: []
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with: 
          toolchain: nightly
          components: clippy rustfmt miri
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Quick Lint
        run: cargo check --all-features
      - name: Lint
        run: cargo clippy --all-features
      - name: Tests
        run: cargo test --all-features
      - name: Machete
        uses: bnjbvr/cargo-machete@main
      - name: Miri Tests
        run: cargo +nightly miri test 
              
